### ISSUE TITLE
Error: undefined method `build' for Dry::Logic::Rule::Predicate:Class

### ISSUE THREAD

**Issue by Vasu1105** [dry-rb/dry-logic#103]
## Describe the bug
This error `Error: undefined method 'build' for Dry::Logic::Rule::Predicate:Class` is coming when the `build` method is called here https://github.com/dry-rb/dry-types/blob/main/lib/dry/types/constraints.rb#L16. Any idea what is wrong here?
## To Reproduce

Provide detailed steps to reproduce, **an executable script would be best**.

## My environment

- Affects my production application: **YES/NO**
- Ruby version: ...
- OS: ...

**Comment by flash-gordon** [comment]
Please upgrade to the latest versions of dry-logic and dry-types, there were changes to how gems are loaded. It's not always possible to coordinate version compatibility between gems.
