### ISSUE TITLE
IRB crash

### ISSUE THREAD

**Issue by vladimirtemnikov** [dry-rb/dry-logic#104]
## Describe the bug

Hello.
Using dry-logic 1.4.0, irb 1.5.0.

As I mentioned in https://github.com/ruby/irb/issues/455, a session crashes if irb's autocomplete feature is enabled.

## To Reproduce

Type `AnyClass.new.` in console.
Other details in irb issue link.

## Expected behavior

No session crash.

**Comment by solnic** [comment]
This is because of #95 that will be addressed in dry-logic 2.0

**Comment by solnic** [comment]
Also see #99 - if there's anything we can do to workaround this for the time being, I'm more than happy to do it

**Comment by vladimirtemnikov** [comment]
@solnic Thank you for response!
I'm not sure, as I see current implementation does not allow to get rid of `respond_to?`, so may be this could be fixed on irb side, or just wait for dry-logic 2.0 🤔

**Comment by solnic** [comment]
@vladimirtemnikov yeah this is unfortunate. In other places people worked around it by just checking arity of the `respond_to?` 😓 I'll be working on dry-logic/schema/validation 2.0.0 shortly after we are done with the release of Hanami 2.0 (which will happen tomorrow).

**Comment by vladimirtemnikov** [comment]
@solnic sounds great, I guess this conflict could wait a bit then.
Thanks for you work! 🚀

**Comment by solnic** [comment]
@vladimirtemnikov I just realized we can simply do this #105

**Comment by vladimirtemnikov** [comment]
@solnic elegant solution! ❤️

**Comment by kris** [comment]
@solnic did you have a target release date for 2.0?

**Comment by solnic** [comment]
@kris 2023 Q1

**Comment by solnic** [comment]
This should work with dry-logic 1.5.0 now 🙂

**Comment by vladimirtemnikov** [comment]
@solnic Awesome! 
Thank you so much again ❤️

**Comment by benjaminoakes** [comment]
Can this be backported to any older versions of dry-logic?  It would be helpful to have this fix on dry-logic 1.3.x
