### ISSUE TITLE
Add a `text?` predicate for validating that a string contains non-whitespace characters

### ISSUE THREAD

**Issue by backus** [dry-rb/dry-logic#42]
I have multiple projects now which use dry-validation. I am finding myself frequently reaching for this custom predicate in each:

``` ruby
module MyProject
  module Predicates
    include Dry::Logic::Predicates

    # Based on https://en.wikipedia.org/wiki/Whitespace_character#Unicode
    # Matches official ASCII and Unicode whitespace as well as characters
    # which are effectively whitespace characters
    effective_whitespace = "\u200B\u200C\u200D\u2060\uFEFF"
    WHITESPACE_PATTERN = /\A[[:space:]#{effective_whitespace}]*\z/

    def self.contains_text?(string)
      WHITESPACE_PATTERN !~ string
    end
    predicate(:contains_text?, &public_method(:contains_text?))
  end
end
```

Usage is usually

``` ruby
Dry::Validation.Schema do
  configure { config.type_specs    = true }
  required(:foo, :str).filled(:str?, :contains_text?)
end
```

Basically I want to assert that the value is a non-empty string with at least one character that isn't whitespace.

This seems generic enough to be a built-in predicate

**Comment by solnic** [comment]
This won't be added. We can consider stripping strings in `Params` by default and then `filled` will work (or any length-checking predicate). Regardless of how we handle this exactly, it will not be implemented in a predicate in dry-logic.
