### ISSUE TITLE
`respond_to?` predicate needs to be renamed

### ISSUE THREAD

**Issue by dgutov** [dry-rb/dry-logic#73]
As discussed in https://github.com/dry-rb/dry-logic/pull/55, its current name overrides `Object#respond_to?` in an incompatible fashion.

We can rename it to `responds_to?`, for example. Just like `includes?` delegates to `include?`.

**Comment by etiennebarrie** [comment]
The same issue exists with `eql?`.
```ruby
h = {}
o = Object.new
def o.hash
  Dry::Logic::Predicates.hash
end
h[o] = true
h[Dry::Logic::Predicates]
# ! => lib/dry/logic/predicates.rb:181:in `eql?': wrong number of arguments (given 1, expected 2) (ArgumentError)
```
